package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.IncomeRecord;

import java.util.List;
import java.util.Map;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKey(IncomeRecord record);

    /**
     * 根据用户标识查看最近投资收益
     * @param paramMap
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByPage(Map<String, Object> paramMap);

    /**
     * 根据用户标识查询用户收益记录总条数
     * @param paramMap
     * @return
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 根据收益状态和收益时间查询收益记录
     * @param i
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByIncomeStatus(int incomeStatus);
}