package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Mar 06 16:40:42 CST 2018
     */
    int updateByPrimaryKey(LoanInfo record);


    Double selectHistoryAverageRate();

    /*
    * 分页查询产品信息列表
    * */
    List<LoanInfo> selectLoanInfoByPage(Map<String, Object> paramMap);

    /**
     * 根据productType查询产品数量
     * @param productType
     * @return
     */
    Long selectLoanInfoCountByProductType(Map<String,Object> map);

    /**
     * 更新产品剩余可投金额
     * @param paramMap
     * @return
     */
    int updateLoanInfoLeftProductMoneyByLoanId(Map<String, Object> paramMap);

    /**
     * 根据产品状态获取产品列表
     * @param i
     * @return
     */
    List<LoanInfo> selectLoanInfoByProductStatus(int productStatus);

}