package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.RechargeRecord;

import java.util.List;
import java.util.Map;

public interface RechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insertSelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    RechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKeySelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKey(RechargeRecord record);
    /*
    * 分页查询充值记录
    * */
    List<RechargeRecord> selectRechargeRecordByPage(Map<String, Object> paramMap);

    /**
     * 根据用户标识查询用户充值记录
     * @param paramMap
     * @return
     */
    Long selectTotalRows(Map<String, Object> paramMap);

    /**
     * 根据充值订单号更新充值状态
     * @return
     */

    int updateRechargeRecordByRechargeNo(RechargeRecord rechargeRecord);

    /**
     * 获取一小时之前的充值记录状态为0 的充值记录信息
     * @param s
     * @return
     */
    List<RechargeRecord> selectRechargeRecordByList(String s);
}