package com.bjpowernode.p2p.mapper.user;

import com.bjpowernode.p2p.model.user.FinanceAccount;

import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Tue Mar 06 16:40:43 CST 2018
     */
    int updateByPrimaryKey(FinanceAccount record);

    /**
     * 根据uid查询用户账户金额
     * @param uid
     * @return
     */
    FinanceAccount selectMyFinanceAcountByUid(int uid);

    /**
     * 更新账户可用余额
     * @param paramMap
     * @return
     */
    int updateAvailableMoneyByUid(Map<String, Object> paramMap);

    /**
     * 收益返还,更新账户可用余额
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByIncomeBack(Map<String, Object> paramMap);

    /**
     * 用户充值:更新账户可用余额
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByRecharge(Map<String, Object> paramMap);
}